import OrderDetailResultModel from '@/models/box-management/shopping-orders/OrderDetailResultModel';
export default class {
    transaction = '';
    boxNo = '';
    customerId = '';
    customerName = '';
    mobile = '';
    payType = 0;
    payTypeName = '';
    invDevice = '';
    invDeviceName = '';
    invDeviceCode = '';
    ordererName = '';
    ordererMobile = '';
    zip = '';
    city = '';
    region = '';
    address = '';
    createTime = '';
    previewDueDate = '';
    shipDate = '';
    devileryTime = '';
    orderTime = '';
    appreciationTime = '';
    returnApplyTime = '';
    rtnDate = '';
    rtnNo = '';
    totalPrice = 0;
    detailsSum = 0;
    details = new Array<OrderDetailResultModel>();
}
